stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  only: master
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de .
    - docker push registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de
  tags: 
    - occloxium-docker

deploy: 
  stage: deploy
  only: 
    - master
  environment:
    name: deployment
    url: https://www.zoomoid.de
  scripts:
    - docker-compose down
    - docker-compose up
  tags:
    - occloxium-shell