stages:
  - build
  - deploy

build:
  only:
    - master
  image: docker:latest
  stage: build
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de .
    - docker push registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de/stable:latest
  tags: 
    - occloxium-docker

build-dev:
  except:
    - master
  image: docker:latest
  stage: build
  script: 
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de .
    - docker push registry.git.rwth-aachen.de/occloxium-webdev/zoomoid.de/experimental:latest
  tags: 
    - occloxium-docker

deploy: 
  only: 
    - master
  stage: deploy
  environment:
    name: deployment
    url: https://www.zoomoid.de
  script:
    - docker-compose down
    - docker-compose up -d
  tags:
    - occloxium-shell

deploy-dev: 
  except: 
    - master
  stage: deploy
  environment:
    name: deployment
    url: https://staging.zoomoid.de
  script:
    - docker-compose -f staging.yml down
    - docker-compose -f staging.yml up -d
  tags:
    - occloxium-shell
